levels: []
race: []
XP: []
Professions: []
fzSpawnChance: 20
fzHealth: 40
fsSpawnChance: 20
ssHealth: 40
ssSpawnChance: 20
ssHealth: 40
zsSpawnChance: 20
zsHealth: 40
ztSpawnChance: 20
ztHealth: 60
stSpawnChance: 20
stHealth: 60
tSpawnChance: 10
tHealth: 80
zkSpawnChance: 10
zkHealth: 80
skSpawnChance: 10
skHealth: 80
zslSpawnChance: 20
zsHealth: 60